# Generated by Django 5.1.14 on 2025-11-12 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('dni_cuit', models.CharField(max_length=20)),
                ('condicion_iva', models.CharField(choices=[('A', 'Resp Insc.'), ('B', 'Consumidor final'), ('C', 'Mono')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('provincia', models.CharField(choices=[('A', 'Ciudad Autónoma de Buenos Aires'), ('B', 'Buenos Aires'), ('C', 'Catamarca'), ('D', 'Chaco'), ('E', 'Chubut'), ('F', 'Córdoba'), ('G', 'Corrientes'), ('H', 'Entre Ríos'), ('I', 'Formosa'), ('J', 'Jujuy'), ('K', 'La Pampa'), ('L', 'La Rioja'), ('M', 'Mendoza'), ('N', 'Misiones'), ('O', 'Neuquén'), ('P', 'Río Negro'), ('Q', 'Salta'), ('R', 'San Juan'), ('S', 'San Luis'), ('T', 'Santa Cruz'), ('U', 'Santa Fe'), ('V', 'Santiago del Estero'), ('W', 'Tierra del Fuego'), ('X', 'Tucumán')], max_length=1)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('historial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facturacion', to='payment.historialcompras')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('instrucciones_adicionales', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_envio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=50)),
                ('apellido', models.CharField(blank=True, default='', max_length=50)),
                ('razon_social', models.CharField(blank=True, default='', max_length=255)),
                ('dni_cuit', models.CharField(blank=True, default='', max_length=20)),
                ('condicion_iva', models.CharField(choices=[('A', 'Resp Insc.'), ('B', 'Consumidor final'), ('C', 'Mono')], max_length=1)),
                ('email_verificado', models.BooleanField(default=False)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('provincia', models.CharField(blank=True, choices=[('A', 'Ciudad Autónoma de Buenos Aires'), ('B', 'Buenos Aires'), ('C', 'Catamarca'), ('D', 'Chaco'), ('E', 'Chubut'), ('F', 'Córdoba'), ('G', 'Corrientes'), ('H', 'Entre Ríos'), ('I', 'Formosa'), ('J', 'Jujuy'), ('K', 'La Pampa'), ('L', 'La Rioja'), ('M', 'Mendoza'), ('N', 'Misiones'), ('O', 'Neuquén'), ('P', 'Río Negro'), ('Q', 'Salta'), ('R', 'San Juan'), ('S', 'San Luis'), ('T', 'Santa Cruz'), ('U', 'Santa Fe'), ('V', 'Santiago del Estero'), ('W', 'Tierra del Fuego'), ('X', 'Tucumán')], default='', max_length=1)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('localidad', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=6, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('recuperar', 'Recuperar'), ('verificar', 'Verificar')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
