# Generated by Django 5.1.15 on 2026-01-19 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Dirección de email')),
                ('razon_social', models.CharField(blank=True, default='', max_length=255)),
                ('dni_cuit', models.CharField(blank=True, default='', max_length=20)),
                ('condicion_iva', models.CharField(choices=[('A', 'Responsable Inscripto'), ('B', 'Consumidor Final'), ('C', 'Monotributo'), ('E', 'Exento'), ('N', 'No Responsable')], default='B', max_length=1)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('provincia', models.CharField(blank=True, choices=[('A', 'Ciudad Autónoma de Buenos Aires'), ('B', 'Buenos Aires'), ('C', 'Catamarca'), ('H', 'Chaco'), ('U', 'Chubut'), ('X', 'Córdoba'), ('W', 'Corrientes'), ('E', 'Entre Ríos'), ('P', 'Formosa'), ('Y', 'Jujuy'), ('L', 'La Pampa'), ('F', 'La Rioja'), ('M', 'Mendoza'), ('N', 'Misiones'), ('Q', 'Neuquén'), ('R', 'Río Negro'), ('I', 'Salta'), ('J', 'San Juan'), ('D', 'San Luis'), ('Z', 'Santa Cruz'), ('S', 'Santa Fe'), ('G', 'Santiago del Estero'), ('V', 'Tierra del Fuego'), ('T', 'Tucumán')], default='', max_length=1)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('localidad', models.CharField(blank=True, default='', max_length=255)),
                ('email_verificado', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('dni_cuit', models.CharField(max_length=20)),
                ('condicion_iva', models.CharField(choices=[('A', 'Responsable Inscripto'), ('B', 'Consumidor Final'), ('C', 'Monotributo'), ('E', 'Exento'), ('N', 'No Responsable')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('provincia', models.CharField(choices=[('A', 'Ciudad Autónoma de Buenos Aires'), ('B', 'Buenos Aires'), ('C', 'Catamarca'), ('H', 'Chaco'), ('U', 'Chubut'), ('X', 'Córdoba'), ('W', 'Corrientes'), ('E', 'Entre Ríos'), ('P', 'Formosa'), ('Y', 'Jujuy'), ('L', 'La Pampa'), ('F', 'La Rioja'), ('M', 'Mendoza'), ('N', 'Misiones'), ('Q', 'Neuquén'), ('R', 'Río Negro'), ('I', 'Salta'), ('J', 'San Juan'), ('D', 'San Luis'), ('Z', 'Santa Cruz'), ('S', 'Santa Fe'), ('G', 'Santiago del Estero'), ('V', 'Tierra del Fuego'), ('T', 'Tucumán')], max_length=1)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facturacion', to='payment.venta')),
            ],
            options={
                'verbose_name': 'Facturación',
                'verbose_name_plural': 'Datos de Facturación',
            },
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('instrucciones_adicionales', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_envio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=6, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('recuperar', 'Recuperar'), ('verificar', 'Verificar')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
