# Generated by Django 5.1.14 on 2025-11-28 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_historialcompras_pagos_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfacturacion',
            name='historial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facturacion', to='payment.venta'),
        ),
    ]
