# Generated by Django 5.0.6 on 2025-03-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_perfilusuario_apellidos_perfilusuario_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='telefono',
        ),
    ]
