# Generated by Django 5.1.14 on 2025-11-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_datosfacturacion_historial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosfacturacion',
            old_name='historial',
            new_name='venta',
        ),
    ]
