# Generated by Django 5.1.7 on 2025-03-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_perfilusuario_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
