# Generated by Django 5.1.15 on 2026-01-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_historial_datosfacturacion_venta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosfacturacion',
            options={'verbose_name': 'Facturación', 'verbose_name_plural': 'Datos de Facturación'},
        ),
    ]
