# Generated by Django 5.1.7 on 2025-03-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_perfilusuario_apellidos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='cuit',
            new_name='dni_cuit',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='dni',
        ),
    ]
