# Generated by Django 5.1.7 on 2025-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_cuit_perfilusuario_dni_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_factura',
            field=models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C')], default='B', max_length=1),
        ),
    ]
