# Generated by Django 5.1.7 on 2025-03-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_perfilusuario_calle_perfilusuario_calle_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cuidad',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
