# Generated by Django 5.1.7 on 2025-03-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_perfilusuario_cuidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_factura',
            field=models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C')], max_length=1),
        ),
    ]
