# Generated by Django 5.1.7 on 2025-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_datosfacturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='guardar_datos',
            field=models.BooleanField(default=False),
        ),
    ]
