# Generated by Django 5.1.7 on 2025-04-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_perfilusuario_guardar_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosfacturacion',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
