# Generated by Django 5.1.8 on 2025-04-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_datosfacturacion_cuidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='cuidad',
            new_name='ciudad',
        ),
    ]
