# Generated by Django 5.1.8 on 2025-04-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_cuidad_perfilusuario_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='guardar_datos',
        ),
    ]
