# Generated by Django 5.1.8 on 2025-04-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_perfilusuario_guardar_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='preferencias_estado_pedido',
        ),
    ]
