# Generated by Django 5.1.10 on 2025-06-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_tokenusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosfacturacion',
            name='tipo_factura',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='tipo_factura',
        ),
        migrations.AddField(
            model_name='datosfacturacion',
            name='condicion_iva',
            field=models.CharField(choices=[('A', 'Resp Insc.'), ('B', 'Consumidor final'), ('C', 'Mono')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='condicion_iva',
            field=models.CharField(choices=[('A', 'Resp Insc.'), ('B', 'Consumidor final'), ('C', 'Mono')], default='B', max_length=1),
        ),
    ]
