# Generated by Django 5.1.10 on 2025-10-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_datosfacturacion_condicion_iva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='token_verificacion',
        ),
        migrations.RemoveField(
            model_name='tokenusers',
            name='token',
        ),
        migrations.AddField(
            model_name='tokenusers',
            name='codigo',
            field=models.CharField(default='', editable=False, max_length=6, unique=True),
        ),
    ]
