# Generated by Django 5.1.10 on 2025-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_perfilusuario_token_verificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='calle',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='calle_detail',
        ),
        migrations.AlterField(
            model_name='tokenusers',
            name='codigo',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenusers',
            name='tipo',
            field=models.CharField(choices=[('recuperar', 'Recuperar'), ('verificar', 'Verificar')], max_length=30),
        ),
    ]
