# Generated by Django 5.1.10 on 2025-10-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_calle_perfilusuario_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='ciudad',
            new_name='localidad',
        ),
    ]
