# Generated by Django 5.1.10 on 2025-10-20 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_rename_ciudad_perfilusuario_localidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosfacturacion',
            old_name='calle',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='datosfacturacion',
            old_name='ciudad',
            new_name='localidad',
        ),
        migrations.RemoveField(
            model_name='datosfacturacion',
            name='calle_detail',
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('instrucciones_adicionales', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_envio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
