# Generated by Django 5.1.10 on 2025-10-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_rename_calle_datosfacturacion_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='preferencias_promociones',
        ),
    ]
