# Generated by Django 5.1.14 on 2025-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_stock', models.CharField(choices=[('libre', 'Sin control de stock'), ('estricto', 'Control de stock')], default='libre', max_length=20)),
                ('mostrar_stock_en_front', models.BooleanField(default=True, help_text='Mostrar cantidad de stock en el sitio.')),
            ],
        ),
        migrations.CreateModel(
            name='DolarConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de dólar',
                'verbose_name_plural': '⚙️ Configuración . Dolar',
            },
        ),
        migrations.CreateModel(
            name='ModoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Modo de mantenimiento',
                'verbose_name_plural': '⚙️ Configuración · Mantenimiento',
            },
        ),
    ]
