# Generated by Django 5.1.15 on 2026-01-19 20:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('titular_cuenta', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('cbu', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('imagen_banco', models.ImageField(blank=True, help_text='Logo del banco. (Opcional)', null=True, upload_to='bancos_logos/')),
            ],
            options={
                'verbose_name': 'Dato Bancario',
                'verbose_name_plural': 'Datos Bancarios',
            },
        ),
        migrations.CreateModel(
            name='EventosPromociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=False)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento en porcentaje (0-100).', max_digits=5, null=True)),
                ('descuento_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento en valor fijo.', max_digits=10, null=True)),
                ('mostrar_en_inicio', models.BooleanField(default=False, help_text='Mostrar en la página de inicio.')),
                ('logo', models.ImageField(blank=True, help_text='Imagen de banner para el evento/promoción.', null=True, upload_to='eventos_banners/')),
            ],
            options={
                'verbose_name': 'Evento / Promoción',
                'verbose_name_plural': 'Eventos y Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_desktop', models.ImageField(upload_to='home/banners/', validators=[core.models.validate_image_size])),
                ('imagen_mobile', models.ImageField(upload_to='home/banners/mobile/', validators=[core.models.validate_image_size])),
                ('url', models.URLField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Banner de la Página de Inicio',
                'verbose_name_plural': 'Banners de la Página de Inicio',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeBannerMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField(blank=True, default='', help_text='Código SVG para el ícono del banner.', null=True, validators=[core.models.HomeBannerMedio.validate_svg])),
                ('tipo', models.CharField(choices=[('garantia', 'Garantía'), ('envio', 'Envío'), ('cuotas', 'Cuotas'), ('personalizado', 'Personalizado')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Banner Medio(Garantia, Envío, Cuotas, Personalizado)',
                'verbose_name_plural': 'Banners Medios(Garantia, Envío, Cuotas, Personalizado)',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeCarouselBento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='home/categorias/', validators=[core.models.validate_image_size])),
                ('tamano', models.CharField(choices=[('default', 'Standard ■'), ('large', 'Grande ▉'), ('tall', 'Alta ▐'), ('wide', 'Ancha ▃')], default='default', max_length=20)),
                ('slide', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Carousel tipo Bento',
                'verbose_name_plural': 'Carousel tipo Bento',
                'ordering': ['slide', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeProductGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(choices=[('recientes', 'Nuevos Ingresos'), ('ofertas', 'Con Descuento'), ('destacados', 'Destacados (Manual)'), ('etiqueta', 'Por Etiqueta Específica'), ('marca', 'Por Marca Específica')], max_length=20)),
            ],
            options={
                'verbose_name': 'Grilla de productos',
                'verbose_name_plural': 'Grillas de productos',
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('banner_principal', 'Banner Principal'), ('grilla', 'Grilla de Productos'), ('bento', 'Carousel Tipo Bento'), ('static_bento', 'Bento Estático'), ('banner_medio', 'Banner Intermedio'), ('marcas', 'Marcas Destacadas'), ('texto_seo', 'Texto SEO')], max_length=50)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la página de inicio.')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la sección está activa.')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Sección(Pagina de Inicio)',
                'verbose_name_plural': 'Secciones(Pagina de Inicio)',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeStaticBento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='home/categorias/', validators=[core.models.validate_image_size])),
                ('color_fondo', models.CharField(default='#ffffff', help_text='Color HEX (ej: #2e6fc3)', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bento Estatico',
                'verbose_name_plural': 'Bento Estatico',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_sandbox', models.BooleanField(default=True, help_text='Indica si se está en modo sandbox (pruebas).')),
                ('public_key', models.CharField(help_text='Clave pública de MercadoPago.', max_length=200)),
                ('access_token', models.CharField(help_text='Token de acceso de MercadoPago.', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración de MercadoPago',
                'verbose_name_plural': 'Configuraciones de MercadoPago',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Mi Tienda', max_length=100)),
                ('modo_stock', models.CharField(choices=[('libre', 'Sin control de stock'), ('estricto', 'Control de stock')], default='libre', max_length=20)),
                ('mostrar_stock_en_front', models.BooleanField(default=False, help_text='Mostrar cantidad de stock en el sitio.')),
                ('borrar_cupon', models.BooleanField(default=False, help_text='Borrar el cupón después de su uso.')),
                ('mantenimiento', models.BooleanField(default=False, help_text='Indica si el sitio está en modo mantenimiento.')),
                ('divisa', models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares Estadounidenses (USD)')], default='ARS', help_text='Divisa utilizada en la tienda.', max_length=3)),
                ('valor_dolar', models.DecimalField(decimal_places=2, default=1.0, help_text='Valor actual del dólar.', max_digits=10)),
                ('maximo_compra', models.PositiveIntegerField(default=10, help_text="Cantidad máxima de productos por compra(Valor tope cuando se usa el 'modo libre').")),
                ('fecha_actualizacion_dolar', models.DateTimeField(auto_now=True)),
                ('fecha_actualizacion_config', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mi Tienda',
                'verbose_name_plural': 'Mi Tienda',
            },
        ),
    ]
