# Generated by Django 5.1.7 on 2025-04-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Modo Mantenimiento',
                'verbose_name_plural': 'Modo Mantenimiento',
            },
        ),
    ]
