# Generated by Django 5.1.15 on 2026-01-19 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarouselbento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_items', to='products.categoria'),
        ),
        migrations.AddField(
            model_name='homecarouselbento',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_items', to='products.marca'),
        ),
        migrations.AddField(
            model_name='homecarouselbento',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_items', to='products.producto'),
        ),
        migrations.AddField(
            model_name='homecarouselbento',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_items', to='products.subcategoria'),
        ),
        migrations.AddField(
            model_name='homeproductgrid',
            name='etiqueta_filtro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.etiquetas'),
        ),
        migrations.AddField(
            model_name='homeproductgrid',
            name='marca_filtro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.marca'),
        ),
        migrations.AddField(
            model_name='homeproductgrid',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids_productos', to='core.homesection'),
        ),
        migrations.AddField(
            model_name='homecarouselbento',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.homesection'),
        ),
        migrations.AddField(
            model_name='homebannermedio',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners_medios', to='core.homesection'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='core.homesection'),
        ),
        migrations.AddField(
            model_name='homestaticbento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_home_items', to='products.categoria'),
        ),
        migrations.AddField(
            model_name='homestaticbento',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_home_items', to='products.marca'),
        ),
        migrations.AddField(
            model_name='homestaticbento',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_home_items', to='products.producto'),
        ),
        migrations.AddField(
            model_name='homestaticbento',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_bento', to='core.homesection'),
        ),
        migrations.AddField(
            model_name='homestaticbento',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_home_items', to='products.subcategoria'),
        ),
    ]
