# Generated by Django 5.1.14 on 2025-11-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DolarConfiguracion',
        ),
        migrations.DeleteModel(
            name='ModoMantenimiento',
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='borrar_cupon',
            field=models.BooleanField(default=False, help_text='Borrar el cupón después de su uso.'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='divisa',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares Estadounidenses (USD)')], default='ARS', help_text='Divisa utilizada en la tienda.', max_length=3),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='fecha_actualizacion_config',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='fecha_actualizacion_dolar',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='mantenimiento',
            field=models.BooleanField(default=False, help_text='Indica si el sitio está en modo mantenimiento.'),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='nombre_tienda',
            field=models.CharField(default='Mi Tienda', max_length=100),
        ),
        migrations.AddField(
            model_name='configuraciontienda',
            name='valor_dolar',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Valor actual del dólar.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuraciontienda',
            name='mostrar_stock_en_front',
            field=models.BooleanField(default=False, help_text='Mostrar cantidad de stock en el sitio.'),
        ),
    ]
