# Generated by Django 5.1.15 on 2026-01-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='color_primario',
            field=models.CharField(default='#1173d4', max_length=7),
        ),
        migrations.AddField(
            model_name='tienda',
            name='color_secundario',
            field=models.CharField(default='#1987ee', max_length=7),
        ),
    ]
