# Generated by Django 5.1.14 on 2025-11-14 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_dolarconfiguracion_delete_modomantenimiento_and_more'),
        ('products', '0002_rename_precio_dolar_producto_precio_divisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosPromociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=False)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento en porcentaje (0-100).', max_digits=5, null=True)),
                ('descuento_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento en valor fijo.', max_digits=10, null=True)),
                ('mostrar_en_inicio', models.BooleanField(default=False, help_text='Mostrar en la página de inicio.')),
                ('etiqueta', models.ForeignKey(help_text='Etiqueta asociada al evento/promoción.', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='products.etiquetas')),
            ],
            options={
                'verbose_name': 'Evento / Promoción',
                'verbose_name_plural': 'Eventos y Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
