# Generated by Django 5.1.7 on 2025-04-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dolarconfiguracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dolarconfiguracion',
            old_name='dolar',
            new_name='valor',
        ),
    ]
