# Generated by Django 5.1.15 on 2026-01-20 17:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tienda_color_primario_tienda_color_secundario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='color_primario',
            field=colorfield.fields.ColorField(default='#1173d4', image_field=None, max_length=25, samples=None, verbose_name='Color Primario'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='color_secundario',
            field=colorfield.fields.ColorField(default='#1987ee', image_field=None, max_length=25, samples=None, verbose_name='Color Secundario'),
        ),
    ]
