# Generated by Django 5.1.14 on 2025-11-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventospromociones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuraciontienda',
            options={'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AddField(
            model_name='eventospromociones',
            name='imagen_banner',
            field=models.ImageField(blank=True, help_text='Imagen de banner para el evento/promoción.', null=True, upload_to='eventos_banners/'),
        ),
    ]
