# Generated by Django 5.1.10 on 2025-11-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dolarconfiguracion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_stock', models.CharField(choices=[('libre', 'Sin control de stock'), ('estricto', 'Control de stock')], default='libre', max_length=20)),
                ('mostrar_stock_en_front', models.BooleanField(default=True, help_text='Mostrar cantidad de stock en el sitio.')),
            ],
        ),
    ]
