# Generated by Django 5.1.14 on 2025-11-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_configuraciontienda_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventospromociones',
            old_name='imagen_banner',
            new_name='logo',
        ),
    ]
