# Generated by Django 5.1.15 on 2026-01-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tienda_color_primario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadopagoconfig',
            name='modo_sandbox',
        ),
        migrations.AlterField(
            model_name='datosbancarios',
            name='alias',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datosbancarios',
            name='banco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='datosbancarios',
            name='cbu',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datosbancarios',
            name='numero_cuenta',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datosbancarios',
            name='titular_cuenta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='tipo',
            field=models.CharField(choices=[('empty', 'Seleccioná una opción'), ('banner_principal', 'Banner Principal'), ('grilla', 'Grilla de Productos'), ('bento', 'Carousel Tipo Bento'), ('static_bento', 'Bento Estático'), ('banner_medio', 'Banner Pequeño')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mercadopagoconfig',
            name='access_token',
            field=models.CharField(default='', help_text='Token de acceso de MercadoPago.', max_length=200),
        ),
        migrations.AlterField(
            model_name='mercadopagoconfig',
            name='public_key',
            field=models.CharField(default='', help_text='Clave pública de MercadoPago.', max_length=200),
        ),
    ]
