# Generated by Django 5.1.15 on 2026-01-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_mercadopagoconfig_modo_sandbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadopagoconfig',
            name='webhook_key',
            field=models.CharField(default='', help_text='Clave para poder recibir pagos.', max_length=200),
        ),
    ]
