# Generated by Django 5.1.14 on 2025-11-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_imagen_banner_eventospromociones_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventospromociones',
            name='etiqueta',
        ),
    ]
