# Generated by Django 5.1.15 on 2026-01-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mercadopagoconfig_webhook_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproductgrid',
            name='criterio',
            field=models.CharField(choices=[('recientes', 'Nuevos Ingresos'), ('ofertas', 'Con Descuento'), ('destacados', 'Destacados (Manual)'), ('etiqueta', 'Por Etiqueta Específica'), ('marca', 'Por Marca Específica'), ('evento', 'Por evento activo')], max_length=20),
        ),
    ]
