# Generated by Django 5.1.14 on 2025-11-20 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_eventospromociones_etiqueta'),
        ('products', '0004_producto_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('banner_principal', 'Banner Principal'), ('ofertas', 'Ofertas'), ('productos_destacados', 'Productos Destacados'), ('categorias', 'Categorías'), ('nuevos_productos', 'Nuevos Productos'), ('banner_medio', 'Banner Intermedio'), ('marcas', 'Marcas Destacadas'), ('texto_seo', 'Texto SEO'), ('custom1', 'Personalizado 1'), ('custom2', 'Personalizado 2')], max_length=50)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la página de inicio.')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la sección está activa.')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='home/categorias/')),
                ('tamano', models.CharField(choices=[('default', 'Standard'), ('large', 'Grande'), ('tall', 'Alta'), ('wide', 'Ancha')], default='default', max_length=20)),
                ('slide', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_items', to='products.categoria')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.homesection')),
            ],
            options={
                'ordering': ['slide', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeBannerMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('garantia', 'Garantía'), ('envio', 'Envío'), ('cuotas', 'Cuotas')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners_medios', to='core.homesection')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_desktop', models.ImageField(upload_to='home/banners/')),
                ('imagen_mobile', models.ImageField(upload_to='home/banners/mobile/')),
                ('url', models.URLField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='core.homesection')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
