# Generated by Django 5.1.14 on 2025-11-20 23:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homesection_homecategoryitem_homebannermedio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebannermedio',
            name='svg',
            field=models.TextField(default='', help_text='Código SVG para el ícono del banner.', validators=[core.models.HomeBannerMedio.validate_svg]),
        ),
        migrations.AlterField(
            model_name='homebannermedio',
            name='tipo',
            field=models.CharField(choices=[('garantia', 'Garantía'), ('envio', 'Envío'), ('cuotas', 'Cuotas'), ('personalizado', 'Personalizado')], max_length=20, unique=True),
        ),
    ]
