# Generated by Django 5.1.14 on 2025-11-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homebannermedio_svg_alter_homebannermedio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebannermedio',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homebannermedio',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
