# Generated by Django 5.1.14 on 2025-11-20 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_homebannermedio_descripcion_and_more'),
        ('products', '0004_producto_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategoryitem',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_items', to='products.subcategoria'),
        ),
    ]
