# Generated by Django 5.1.14 on 2025-11-21 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_homecategoryitem_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeReseñas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=150, null=True)),
                ('calificaciones', models.PositiveBigIntegerField(default=0, help_text='Calificacion minima para mostrar reseñas. (0 incluye todo tipo de reseñas)')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='core.homesection')),
            ],
            options={
                'verbose_name': 'Reseñas de Clientes',
                'verbose_name_plural': 'Reseñas de Clientes',
            },
        ),
    ]
