# Generated by Django 5.1.14 on 2025-11-21 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_homereseñas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ['orden'], 'verbose_name': 'Banner de la Página de Inicio', 'verbose_name_plural': 'Banners de la Página de Inicio'},
        ),
        migrations.AlterModelOptions(
            name='homebannermedio',
            options={'ordering': ['orden'], 'verbose_name': 'Banner Medio(Garantia, Envío, Cuotas, Personalizado)', 'verbose_name_plural': 'Banners Medios(Garantia, Envío, Cuotas, Personalizado)'},
        ),
        migrations.AlterModelOptions(
            name='homecategoryitem',
            options={'ordering': ['slide', 'orden'], 'verbose_name': 'Carousel de Categorías|Subcategorias', 'verbose_name_plural': 'Carousel de Categorías|Subcategorias'},
        ),
        migrations.AlterModelOptions(
            name='homesection',
            options={'ordering': ['orden'], 'verbose_name': 'Sección(Pagina de Inicio)', 'verbose_name_plural': 'Secciones(Pagina de Inicio)'},
        ),
        migrations.RemoveField(
            model_name='homereseñas',
            name='orden',
        ),
    ]
