# Generated by Django 5.1.14 on 2025-11-27 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_homebanner_options_and_more'),
        ('products', '0005_proveedor_ingresostock_lotestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=150, null=True)),
                ('etiqueta', models.ManyToManyField(related_name='carouseles_home', to='products.etiquetas')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carouseles', to='core.homesection')),
            ],
            options={
                'verbose_name': 'Carrusel Personalizado',
                'verbose_name_plural': 'Carruseles Personalizados',
            },
        ),
    ]
