# Generated by Django 5.1.14 on 2025-11-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_homecarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontienda',
            name='maximo_compra',
            field=models.PositiveIntegerField(default=10, help_text="Cantidad máxima de productos por compra(Valor tope cuando se usa el 'modo libre')."),
        ),
    ]
