# Generated by Django 5.1.14 on 2025-11-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_configuraciontienda_maximo_compra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfiguracionTienda',
            new_name='Tienda',
        ),
    ]
