# Generated by Django 5.1.15 on 2026-01-15 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_configuraciontienda_tienda'),
        ('products', '0011_alter_colorproducto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('titular_cuenta', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('cbu', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('imagen_banco', models.ImageField(blank=True, help_text='Logo del banco. (Opcional)', null=True, upload_to='bancos_logos/')),
            ],
            options={
                'verbose_name': 'Dato Bancario',
                'verbose_name_plural': 'Datos Bancarios',
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_sandbox', models.BooleanField(default=True, help_text='Indica si se está en modo sandbox (pruebas).')),
                ('public_key', models.CharField(help_text='Clave pública de MercadoPago.', max_length=200)),
                ('access_token', models.CharField(help_text='Token de acceso de MercadoPago.', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración de MercadoPago',
                'verbose_name_plural': 'Configuraciones de MercadoPago',
            },
        ),
        migrations.AlterModelOptions(
            name='tienda',
            options={'verbose_name': 'Mi Tienda', 'verbose_name_plural': 'Mi Tienda'},
        ),
        migrations.AlterField(
            model_name='homesection',
            name='tipo',
            field=models.CharField(choices=[('banner_principal', 'Banner Principal'), ('grilla', 'Grilla de Productos'), ('categorias', 'Categorías'), ('banner_medio', 'Banner Intermedio'), ('marcas', 'Marcas Destacadas'), ('texto_seo', 'Texto SEO')], max_length=50),
        ),
        migrations.CreateModel(
            name='HomeProductGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(choices=[('recientes', 'Nuevos Ingresos'), ('ofertas', 'Con Descuento'), ('destacados', 'Destacados (Manual)'), ('etiqueta', 'Por Etiqueta Específica'), ('mas_vendidos', 'Más Vendidos')], max_length=20)),
                ('etiqueta_filtro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.etiquetas')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids_productos', to='core.homesection')),
            ],
            options={
                'verbose_name': 'Grilla de productos',
                'verbose_name_plural': 'Grillas de productos',
            },
        ),
        migrations.DeleteModel(
            name='HomeCarousel',
        ),
    ]
