# Generated by Django 5.1.15 on 2026-01-16 00:02

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_datosbancarios_mercadopagoconfig_and_more'),
        ('products', '0011_alter_colorproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproductgrid',
            name='marca_filtro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.marca'),
        ),
        migrations.AlterField(
            model_name='homebannermedio',
            name='svg',
            field=models.TextField(blank=True, default='', help_text='Código SVG para el ícono del banner.', null=True, validators=[core.models.HomeBannerMedio.validate_svg]),
        ),
        migrations.AlterField(
            model_name='homeproductgrid',
            name='criterio',
            field=models.CharField(choices=[('recientes', 'Nuevos Ingresos'), ('ofertas', 'Con Descuento'), ('destacados', 'Destacados (Manual)'), ('etiqueta', 'Por Etiqueta Específica'), ('marca', 'Por Marca Específica')], max_length=20),
        ),
    ]
