# Generated by Django 5.1.15 on 2026-01-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_homeproductgrid_marca_filtro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium')], default='basico', help_text='Plan actual de la tienda.', max_length=20),
        ),
    ]
