# Generated by Django 5.1.15 on 2026-01-16 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tienda_plan'),
        ('products', '0011_alter_colorproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategoryitem',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_items', to='products.marca'),
        ),
        migrations.AddField(
            model_name='homecategoryitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_items', to='products.producto'),
        ),
    ]
