# Generated by Django 5.1.15 on 2026-01-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_homecategoryitem_marca_homecategoryitem_producto'),
        ('products', '0011_alter_colorproducto_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeCategoryItem',
            new_name='HomeCarouselBento',
        ),
        migrations.AlterModelOptions(
            name='homecarouselbento',
            options={'ordering': ['slide', 'orden'], 'verbose_name': 'Carousel tipo Bento', 'verbose_name_plural': 'Carousel tipo Bento'},
        ),
    ]
