# Generated by Django 5.1.15 on 2026-01-18 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_homecategoryitem_homecarouselbento_and_more'),
        ('products', '0011_alter_colorproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarouselbento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_items', to='products.categoria'),
        ),
        migrations.AlterField(
            model_name='homecarouselbento',
            name='tamano',
            field=models.CharField(choices=[('default', 'Standard ■'), ('large', 'Grande ▉'), ('tall', 'Alta ▐'), ('wide', 'Ancha ▃')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='tipo',
            field=models.CharField(choices=[('banner_principal', 'Banner Principal'), ('grilla', 'Grilla de Productos'), ('bento', 'Carousel Tipo Bento'), ('banner_medio', 'Banner Intermedio'), ('marcas', 'Marcas Destacadas'), ('texto_seo', 'Texto SEO')], max_length=50),
        ),
    ]
