# Generated by Django 5.1.15 on 2026-01-18 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_homecarouselbento_categoria_and_more'),
        ('products', '0011_alter_colorproducto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticBento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='home/categorias/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_home_items', to='products.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_home_items', to='products.marca')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_home_items', to='products.producto')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_bento', to='core.homesection')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_home_items', to='products.subcategoria')),
            ],
            options={
                'verbose_name': 'Bento Estatico',
                'verbose_name_plural': 'Bento Estatico',
                'ordering': ['orden'],
            },
        ),
    ]
