# Generated by Django 5.1.15 on 2026-01-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_staticbento'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticbento',
            name='color_fondo',
            field=models.CharField(default='#ffffff', help_text='Color HEX (ej: #2e6fc3)', max_length=7),
        ),
    ]
