# Generated by Django 5.1.15 on 2026-01-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_staticbento_color_fondo'),
        ('products', '0011_alter_colorproducto_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaticBento',
            new_name='HomeStaticBento',
        ),
    ]
