# Generated by Django 5.1.15 on 2026-01-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_staticbento_homestaticbento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='tipo',
            field=models.CharField(choices=[('banner_principal', 'Banner Principal'), ('grilla', 'Grilla de Productos'), ('bento', 'Carousel Tipo Bento'), ('static_bento', 'Bento Estático'), ('banner_medio', 'Banner Intermedio'), ('marcas', 'Marcas Destacadas'), ('texto_seo', 'Texto SEO')], max_length=50),
        ),
        migrations.DeleteModel(
            name='HomeReseñas',
        ),
    ]
