# Generated by Django 5.1.15 on 2026-01-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_homesection_tipo_delete_homereseñas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='plan',
        ),
    ]
