# Generated by Django 5.0.6 on 2024-06-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_imagenproducto_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='products.categoria'),
        ),
    ]
