# Generated by Django 5.0.6 on 2024-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_producto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='specs',
            field=models.BooleanField(default=False),
        ),
    ]
