# Generated by Django 5.1.15 on 2026-04-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comprobantes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('no verificado', 'No verificado')], default='no verificado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=6, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='DatosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(default='', max_length=100)),
                ('titular_cuenta', models.CharField(default='', max_length=100)),
                ('numero_cuenta', models.CharField(default='', max_length=50)),
                ('cbu', models.CharField(default='', max_length=50)),
                ('alias', models.CharField(default='', max_length=50)),
                ('imagen_banco', models.ImageField(blank=True, help_text='Logo del banco. (Opcional)', null=True, upload_to='bancos_logos/')),
            ],
            options={
                'verbose_name': 'Dato Bancario',
                'verbose_name_plural': 'Datos Bancarios',
            },
        ),
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('dni_cuit', models.CharField(max_length=20)),
                ('condicion_iva', models.CharField(choices=[('A', 'Responsable Inscripto'), ('B', 'Consumidor Final'), ('C', 'Monotributo'), ('E', 'Exento'), ('N', 'No Responsable')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('provincia', models.CharField(choices=[('A', 'Ciudad Autónoma de Buenos Aires'), ('B', 'Buenos Aires'), ('C', 'Catamarca'), ('H', 'Chaco'), ('U', 'Chubut'), ('X', 'Córdoba'), ('W', 'Corrientes'), ('E', 'Entre Ríos'), ('P', 'Formosa'), ('Y', 'Jujuy'), ('L', 'La Pampa'), ('F', 'La Rioja'), ('M', 'Mendoza'), ('N', 'Misiones'), ('Q', 'Neuquén'), ('R', 'Río Negro'), ('I', 'Salta'), ('J', 'San Juan'), ('D', 'San Luis'), ('Z', 'Santa Cruz'), ('S', 'Santa Fe'), ('G', 'Santiago del Estero'), ('V', 'Tierra del Fuego'), ('T', 'Tucumán')], max_length=1)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Facturación',
                'verbose_name_plural': 'Datos de Facturación',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(default='', help_text='Clave pública de MercadoPago.', max_length=200)),
                ('access_token', models.CharField(default='', help_text='Token de acceso de MercadoPago.', max_length=200)),
                ('webhook_key', models.CharField(default='', help_text='Clave para poder recibir pagos.', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración de MercadoPago',
                'verbose_name_plural': 'Configuraciones de MercadoPago',
            },
        ),
        migrations.CreateModel(
            name='PagoRecibidoMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('tipo', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('transferencia', 'Transferencia')], default='mercado_pago', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado'), ('arrepentido', 'Arrepentido'), ('listo para retirar', 'Listo para retirar'), ('enviado', 'Enviado')], default='pendiente', max_length=20)),
                ('forma_de_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('requiere_revision', models.BooleanField(default=True)),
                ('pagos', models.ManyToManyField(blank=True, editable=False, to='payment.pagorecibidomp')),
            ],
        ),
    ]
