# Generated by Django 5.1.14 on 2025-11-12 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=6, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagoRecibidoMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.JSONField()),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente🟡'), ('confirmado', 'Confirmado🟢'), ('rechazado', 'Rechazado🔴'), ('listo para retirar', 'Listo para retirar✔️'), ('enviado', 'Enviado🟣'), ('finalizado', 'Finalizado⚪'), ('arrepentido', 'Arrepentido⭕')], default='pendiente', max_length=20)),
                ('forma_de_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('requiere_revision', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_compras', to=settings.AUTH_USER_MODEL)),
                ('pagos', models.ManyToManyField(blank=True, editable=False, to='payment.pagorecibidomp')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='payment.historialcompras')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comprobantes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('no verificado', 'No verificado')], default='no verificado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('historial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='payment.historialcompras')),
            ],
        ),
        migrations.CreateModel(
            name='TicketDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='payment.historialcompras')),
            ],
        ),
    ]
