# Generated by Django 5.1.14 on 2025-11-28 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompras',
            name='pagos',
        ),
        migrations.RemoveField(
            model_name='historialcompras',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.JSONField()),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente🟡'), ('confirmado', 'Confirmado🟢'), ('rechazado', 'Rechazado🔴'), ('finalizado', 'Finalizado⚪'), ('arrepentido', 'Arrepentido⭕'), ('listo para retirar', 'Listo para retirar✔️'), ('enviado', 'Enviado🟣')], default='pendiente', max_length=20)),
                ('forma_de_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('requiere_revision', models.BooleanField(default=True)),
                ('pagos', models.ManyToManyField(blank=True, editable=False, to='payment.pagorecibidomp')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comprobantetransferencia',
            name='historial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='payment.venta'),
        ),
        migrations.AlterField(
            model_name='estadopedido',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='payment.venta'),
        ),
        migrations.AlterField(
            model_name='ticketdepago',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='payment.venta'),
        ),
    ]
