# Generated by Django 5.1.15 on 2026-04-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosfacturacion',
            name='telefono',
        ),
    ]
