# Generated by Django 5.1.14 on 2025-11-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_historialcompras_pagos_and_more'),
        ('users', '0002_alter_datosfacturacion_historial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialCompras',
        ),
    ]
