# Generated by Django 5.1.14 on 2025-11-28 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_delete_historialcompras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobantetransferencia',
            old_name='historial',
            new_name='venta',
        ),
        migrations.RenameField(
            model_name='estadopedido',
            old_name='historial',
            new_name='venta',
        ),
        migrations.RenameField(
            model_name='ticketdepago',
            old_name='historial',
            new_name='venta',
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
    ]
