# Generated by Django 5.1.15 on 2026-04-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_datosfacturacion_telefono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComprobanteTransferencia',
        ),
    ]
