# Generated by Django 5.1.15 on 2026-04-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_ventadetalle_color_ventadetalle_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdepago',
            name='tipo',
            field=models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('transferencia', 'Transferencia')], default='mercado_pago', max_length=20),
        ),
    ]
