# Generated by Django 5.0.6 on 2025-03-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_historialcompras_detallecompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecompra',
            old_name='producto',
            new_name='pedido',
        ),
    ]
