# Generated by Django 5.1.15 on 2026-04-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_delete_comprobantetransferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosfacturacion',
            name='email',
        ),
    ]
