# Generated by Django 5.1.7 on 2025-03-19 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_producto_detallecompra_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos', models.JSONField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='historial',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='historialcompras',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='historialcompras',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='HistorialCompras',
        ),
    ]
