# Generated by Django 5.1.14 on 2025-11-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_venta_productos_ventadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
