# Generated by Django 5.1.15 on 2026-04-20 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payment', '0005_remove_datosfacturacion_email'),
        ('products', '0003_alter_ajustestock_venta_alter_movimientostock_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadopedido',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='pagos',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='venta',
        ),
        migrations.AlterField(
            model_name='ticketdepago',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.venta'),
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='variante',
        ),
        migrations.DeleteModel(
            name='DatosFacturacion',
        ),
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='VentaDetalle',
        ),
    ]
