# Generated by Django 5.1.15 on 2026-01-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_ventadetalle_imagen_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupon',
            options={'verbose_name': 'Cupón', 'verbose_name_plural': 'Cupones'},
        ),
        migrations.AlterModelOptions(
            name='estadopedido',
            options={'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='ticketdepago',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ventadetalle',
            options={'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado'), ('arrepentido', 'Arrepentido'), ('listo para retirar', 'Listo para retirar'), ('enviado', 'Enviado')], default='pendiente', max_length=20),
        ),
    ]
