# Generated by Django 5.1.7 on 2025-03-23 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_pagorecibido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('preparando pedido', 'Preparando pedido'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialcompras',
            name='token_consulta',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
