# Generated by Django 5.1.7 on 2025-03-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_historialcompras_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagorecibido',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
