# Generated by Django 5.1.7 on 2025-03-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_pagorecibido_external_reference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagoRecibido',
            new_name='PagoRecibidoMP',
        ),
        migrations.RenameField(
            model_name='historialcompras',
            old_name='total_pagado',
            new_name='total_compra',
        ),
    ]
