# Generated by Django 5.1.7 on 2025-03-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_rename_pagorecibido_pagorecibidomp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompras',
            name='forma_de_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado pago', 'Mercado Pago'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
    ]
