# Generated by Django 5.1.7 on 2025-03-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_remove_historialcompras_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompras',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
