# Generated by Django 5.1.7 on 2025-03-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_historialcompras_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagorecibidomp',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
