# Generated by Django 5.1.7 on 2025-03-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_pagorecibidomp_payer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='pagos',
            field=models.ManyToManyField(blank=True, editable=False, to='payment.pagorecibidomp'),
        ),
    ]
