# Generated by Django 5.1.7 on 2025-03-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_historialcompras_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='comprobantes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('historial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='payment.historialcompras')),
            ],
        ),
    ]
