# Generated by Django 5.1.7 on 2025-04-01 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_comprobantetransferencia_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobantetransferencia',
            old_name='imagen',
            new_name='file',
        ),
    ]
