# Generated by Django 5.1.7 on 2025-04-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_historialcompras_recibir_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompras',
            name='payment_id',
        ),
    ]
