# Generated by Django 5.1.8 on 2025-04-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_alter_historialcompras_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantetransferencia',
            name='aprobado',
        ),
        migrations.AddField(
            model_name='comprobantetransferencia',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('no verificado', 'No verificado')], default='no verificado', max_length=20),
        ),
        migrations.AddField(
            model_name='historialcompras',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
