# Generated by Django 5.1.8 on 2025-04-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_remove_comprobantetransferencia_aprobado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompras',
            name='verificado',
        ),
        migrations.AddField(
            model_name='historialcompras',
            name='estado_staff',
            field=models.CharField(choices=[('no verificado', 'No verificado'), ('revision en curso', 'Revisión en curso'), ('esperando respuesta', 'Esperando respuesta del cliente'), ('pedido realizado', 'Pedido realizado al proveedor'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='no verificado', max_length=50),
        ),
    ]
