# Generated by Django 5.1.8 on 2025-05-01 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_alter_historialcompras_estado_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompras',
            name='estado_staff',
        ),
        migrations.AddField(
            model_name='historialcompras',
            name='requiere_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historialcompras',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente🟡'), ('confirmado', 'Confirmado🟢'), ('rechazado', 'Rechazado🔴'), ('preparando pedido', 'Preparando pedido🔵'), ('retiro listo', 'Listo para retirar✔️'), ('enviado', 'Enviado🟣'), ('finalizado', 'Finalizado⚪'), ('arrepentido', 'Arrepentido⭕')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='payment.historialcompras')),
            ],
        ),
    ]
