# Generated by Django 5.1.8 on 2025-05-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_remove_historialcompras_estado_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente🟡'), ('confirmado', 'Confirmado🟢'), ('rechazado', 'Rechazado🔴'), ('preparando pedido', 'Preparando pedido🔵'), ('listo para retirar', 'Listo para retirar✔️'), ('enviado', 'Enviado🟣'), ('finalizado', 'Finalizado⚪'), ('arrepentido', 'Arrepentido⭕')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialcompras',
            name='requiere_revision',
            field=models.BooleanField(default=True),
        ),
    ]
