# Generated by Django 5.1.8 on 2025-06-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
