# Generated by Django 5.1.10 on 2025-07-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_alter_cupon_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='forma_de_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado pago', 'Mercado Pago'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], default='efectivo', max_length=20),
        ),
        migrations.CreateModel(
            name='PagoMixtoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('transferencia', 'Transferencia'), ('mercadopago', 'Mercado pago')], default='transferencia', max_length=20)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='payment.historialcompras')),
            ],
        ),
    ]
