# Generated by Django 5.1.10 on 2025-07-08 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0031_alter_historialcompras_forma_de_pago_pagomixtoticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantetransferencia',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='payment.pagomixtoticket'),
        ),
    ]
