# Generated by Django 5.1.10 on 2025-07-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_comprobantetransferencia_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomixtoticket',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
