# Generated by Django 5.1.10 on 2025-07-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_pagomixtoticket_merchant_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagoMixtoTicket',
            new_name='TicketDePago',
        ),
    ]
