# Generated by Django 5.1.10 on 2025-07-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_rename_pagomixtoticket_ticketdepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='forma_de_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercadopago', 'Mercado Pago'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], default='efectivo', max_length=20),
        ),
    ]
