# Generated by Django 5.1.10 on 2025-07-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_alter_historialcompras_forma_de_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantetransferencia',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='ticketdepago',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='ticketdepago',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
