# Generated by Django 5.1.10 on 2025-10-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_remove_comprobantetransferencia_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompras',
            name='recibir_mail',
        ),
        migrations.AlterField(
            model_name='historialcompras',
            name='forma_de_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercadopago', 'Mercado Pago'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20),
        ),
    ]
