# Generated by Django 5.1.10 on 2025-10-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0037_remove_historialcompras_recibir_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente🟡'), ('confirmado', 'Confirmado🟢'), ('rechazado', 'Rechazado🔴'), ('listo para retirar', 'Listo para retirar✔️'), ('enviado', 'Enviado🟣'), ('finalizado', 'Finalizado⚪'), ('arrepentido', 'Arrepentido⭕')], default='pendiente', max_length=20),
        ),
    ]
