# Generated by Django 5.1.10 on 2025-10-21 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0038_alter_historialcompras_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompras',
            name='token_consulta',
        ),
        migrations.AlterField(
            model_name='historialcompras',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_compras', to=settings.AUTH_USER_MODEL),
        ),
    ]
