# Generated by Django 5.1.10 on 2025-11-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0039_remove_historialcompras_token_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdepago',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketdepago',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
    ]
