# Generated by Django 5.1.7 on 2025-03-23 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_completa', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=50)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_envio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
