# Generated by Django 5.1.7 on 2025-03-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosenvio',
            name='direccion_completa',
        ),
    ]
