"""
Django settings for amt project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ

# Inicializar environ
env = environ.Env()
environ.Env.read_env(os.path.join(os.path.dirname(__file__), ".env"))

# Cargar la variable de entorno del archivo .env
MERCADOPAGO_ACCESS_TOKEN = env("MERCADOPAGO_ACCESS_TOKEN")
MP_WEBHOOK_KEY = env("MP_WEBHOOK_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&r$abfh2yec)-#l^r(^^z*0-+cv!(5lr(2@zmfct65f7^m!4jz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ! Actualizar el HOST con el dominio
ALLOWED_HOSTS = ['ed59-181-228-88-24.ngrok-free.app','127.0.0.1']

# ! Verificar las correspondencias
CSRF_TRUSTED_ORIGINS = [
    "https://ed59-181-228-88-24.ngrok-free.app"
]

# ! Falta verificar que la url recibida por MP sea la correcta, Agregar SECRET KEY A .evn
# ! Verificar la calidad de la integracion de MP
# ! Pobar la seguridad de la pagina

# * Sessions
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 86400
SESSION_COOKIE_HTTPONLY = True

# ! Poner en TRUE al momento de salir a produccion
SESSION_COOKIE_SECURE = False

# Application definition

INSTALLED_APPS = [
    "django_user_agents",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'products',
    'core',
    'cart',
    'users',
    'payment'
]

MIDDLEWARE = [
    "django_user_agents.middleware.UserAgentMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.carrito_total',
            ],
        },
    },
]

WSGI_APPLICATION = 'amt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Asegúrate de importar os o usar Path para definir BASE_DIR
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_URL = "http://127.0.0.1:8000"

# Configuración de SMTP para enviar emails con Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'santiaguirre.lam@gmail.com'  # Reemplázalo con tu dirección de Gmail
EMAIL_HOST_PASSWORD = 'aluc xeog iyiq lkur'  # Usa una contraseña de aplicación en vez de tu contraseña normal

# Configurar la URL de login
LOGIN_URL = "/usuario/login/"