# Generated by Django 5.1.8 on 2025-04-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_dolar_dolarconfiguracion_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dolarconfiguracion',
            options={'verbose_name': 'Configuración de dólar', 'verbose_name_plural': '⚙️ Configuración . Dolar'},
        ),
        migrations.AlterModelOptions(
            name='modomantenimiento',
            options={'verbose_name': 'Modo de mantenimiento', 'verbose_name_plural': '⚙️ Configuración · Mantenimiento'},
        ),
    ]
