"""
Django settings for twinstore project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
import os
import environ
from csp.constants import NONCE

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
#  * Inicializar environ
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

#  * Cargar la variable de entorno del archivo .env
MERCADOPAGO_PERCENTAJE = 0.0642
MERCADOPAGO_COMMISSION = (MERCADOPAGO_PERCENTAJE*(1.315))+1
DJANGO_SECRET_KEY = env("DJANGO_SECRET_KEY")
SECRET_KEY = DJANGO_SECRET_KEY

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

DEBUG = env("DEBUG").lower() == "true"

# * NGROK para pruebas externas
NGROK_URL = None

# * Host
SITE_URL = "twinstore.com.ar"

ALLOWED_HOSTS = ['.localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    f"https://twinstore.com.ar", "https://www.twinstore.com.ar",
]

if NGROK_URL:
    ALLOWED_HOSTS += [NGROK_URL]
    CSRF_TRUSTED_ORIGINS += [f"https://{NGROK_URL}"]
    SITE_URL = NGROK_URL

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 86400
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Strict"

SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

X_FRAME_OPTIONS = "SAMEORIGIN"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = False

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'core.middleware.mantenimiento.MantenimientoGlobalMiddleware',
]

SHARED_APPS = (
    'django_tenants',
    'customers',
    'website',
    
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    
    'django_cleanup.apps.CleanupConfig',
    'compressor',
    'django_extensions',
    'csp',
    'colorfield'
)

if DEBUG:
    SHARED_APPS += ("debug_toolbar",)
    MIDDLEWARE.insert(1, "debug_toolbar.middleware.DebugToolbarMiddleware")

TENANT_APPS = (
    'unfold',
    'unfold.contrib.import_export',
    'django.contrib.admin',
    
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'axes',
    
    'rest_framework',

    'import_export',
    'django.contrib.sitemaps',

    'users',
    'core',
    'products',
    'cart',
    'payment',
    'dashboard',
    'shipping'
)

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']
AXES_FAILURE_LIMIT = 500
AXES_COOLOFF_TIME = 1
AXES_RESET_ON_SUCCESS = True

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ["'self'"],
        "style-src": [
            "'self'",
            "'unsafe-inline'",
            "https://fonts.googleapis.com"
        ],
        "script-src": [
            "'self'",
            NONCE,
            "'unsafe-eval'",
        ],
        "font-src": [
            "'self'",
            "https://fonts.gstatic.com",
            "data:"
        ],
        "img-src": ["'self'", "data:"],
        "frame-src": [
            "'self'",
            "https://www.google.com",
            "https://maps.google.com",
        ],
        "object-src": ["'none'"],
        "base-uri": ["'self'"]
    }
}

ROOT_URLCONF = 'config.urls_tenants'
PUBLIC_SCHEMA_URLCONF = 'config.urls_public'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.carrito_total',
                'cart.context_processors.limpiar_checkout',
                'core.context_processors.evento_activo_context',
                'core.context_processors.config_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
    'anon': '10/minute',
    'user': '100/minute',

    'carrito': '30/minute',
    'calcular_pedido': '15/minute',
    'solicitar_comprobante': '10/minute',
    'modal_users': '15/minute',
    'toggle_notificaciones': '10/hour',
    'enviar_wtap': '10/day',
    'filtros_dinamicos': '30/minute',
    'prediccion_busqueda': '60/minute',
    'micuenta': '20/minute',
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] if not DEBUG else [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]
}

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': env("DB_NAME"),
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWORD"),
        'HOST': env("DB_HOST"),
        'PORT': env("DB_PORT"),
    }
}

TENANT_MODEL = "customers.Client"
TENANT_DOMAIN_MODEL = "customers.Domain"

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "users.validators.StrongPasswordValidator"},
]

# Static files (CSS, JavaScript, Images)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    'compressor.finders.CompressorFinder',
]

AUTH_USER_MODEL = 'users.User'

COMPRESS_ENABLED = not DEBUG
COMPRESS_OFFLINE = not DEBUG

COMPRESS_CSS_FILTERS = [
    "compressor.filters.css_default.CssAbsoluteFilter",
    "compressor.filters.cssmin.CSSMinFilter",
]

COMPRESS_JS_FILTERS = [
    "compressor.filters.jsmin.JSMinFilter",
]

COMPRESS_OUTPUT_DIR = "CACHE"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")
CELERY_TIMEZONE = 'America/Argentina/Buenos_Aires'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# * Argentina !
LANGUAGE_CODE = 'es-ar'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Amazon SES
AWS_SES_ACCESS_KEY_ID = env("AWS_SES_ACCESS_KEY_ID")
AWS_SES_SECRET_ACCESS_KEY = env("AWS_SES_SECRET_ACCESS_KEY")
AWS_SES_REGION_NAME = env("AWS_SES_REGION_NAME")
AWS_SES_SOURCE_EMAIL = env("AWS_SES_SOURCE_EMAIL")

# CACHES
if DEBUG:
    CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-twinstore-cache',
        'KEY_FUNCTION': 'core.utils.make_tenant_key',
    }
}
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': 'redis://redis:6379/1',
            'KEY_FUNCTION': 'core.utils.make_tenant_key',
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
            }
        }
    }

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file_mercadopago": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "mercadopago.log",
            "formatter": "verbose",
            "level": "INFO",
        },
    },
    "loggers": {
        "mercadopago": {
            "handlers": ["file_mercadopago"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

INTERNAL_IPS = [
    '127.0.0.1',
]

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Twinstore Admin",
    "SITE_HEADER": "Twinstore",
    "SITE_SYMBOL": "speed",
    "DASHBOARD_CALLBACK": "dashboard.views.dashboard_callback",
    "ENVIRONMENT": "dashboard.views.environment_callback",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("img/favicon.ico"),
        },
    ],
    "SITE_DROPDOWN": [
        {
            "icon": "diamond",
            "title": _("Volver al sitio"),
            "link": "/",
        },
        {
            "icon": "build_circle",
            "title": _("Activar/Desactivar Mantenimiento"),
            "link": reverse_lazy("core:toggle_mantenimiento"),
        },
    ],
    "COLORS": {
        "base": {
            "50": "oklch(98.5% .002 247.839)",
            "100": "oklch(96.7% .003 264.542)",
            "200": "oklch(92.8% .006 264.531)",
            "300": "oklch(87.2% .01 258.338)",
            "400": "oklch(70.7% .022 261.325)",
            "500": "oklch(55.1% .027 264.364)",
            "600": "oklch(44.6% .03 256.802)",
            "700": "oklch(37.3% .034 259.733)",
            "800": "oklch(27.8% .033 256.848)",
            "900": "oklch(21% .034 264.665)",
            "950": "oklch(13% .028 261.692)",
        },
        "primary": {
            "50": "oklch(97% .014 254.604)",
            "100": "oklch(93.2% .032 255.585)",
            "200": "oklch(88.2% .059 254.128)",
            "300": "oklch(80.9% .105 251.813)",
            "400": "oklch(70.7% .165 254.624)",
            "500": "oklch(62.3% .214 259.815)",
            "600": "oklch(54.6% .245 262.881)",
            "700": "oklch(48.8% .243 264.376)",
            "800": "oklch(42.4% .199 265.638)",
            "900": "oklch(37.9% .146 265.522)",
            "950": "oklch(28.2% .091 267.935)",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
    "SIDEBAR": {
        "show_all_applications": True,
        "navigation": [
            {
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Tu tienda"),
                "separator": True,
                "items": [
                    {
                        "title": _("Tienda"),
                        "icon": "shopping_bag",
                        "link": reverse_lazy('admin:core_tienda_change', args=[1]),
                    },
                    {
                        "title": _("Eventos y promociones"),
                        "icon": "featured_seasonal_and_gifts",
                        "link": reverse_lazy('admin:core_eventospromociones_changelist'),
                    },
                    {
                        "title": _("Cupones"),
                        "icon": "confirmation_number",
                        "link": reverse_lazy('admin:payment_cupon_changelist'),
                    },
                ],
            },
            {
                "title": _("Ventas y usuarios"),
                "separator": True,
                "items": [
                    {
                        "title": _("Ventas"),
                        "icon": "inventory_2",
                        "link": reverse_lazy('admin:payment_venta_changelist'),
                        "badge": "dashboard.views.ventas_verificacion",
                        "badge_variant": "info",
                        "badge_style": "solid",
                    },
                ]
            },
            {
                "title": _("Gestión de productos"),
                "separator": True,
                "items": [
                    {
                        "title": _("Productos"),
                        "icon": "inventory",
                        "link": reverse_lazy('admin:products_producto_changelist'),
                    },
                    {
                        "title": _("Proveedores"),
                        "icon": "local_shipping",
                        "link": reverse_lazy('admin:products_proveedor_changelist'),
                    },
                    {
                        "title": _("Ingresar Stock"),
                        "icon": "category",
                        "link": reverse_lazy('admin:products_ingresostock_changelist'),
                        "permission": "core.permissions.ingreso_stock",
                    },
                    {
                        "title": _("Lotes de Stock"),
                        "icon": "view_list",
                        "link": reverse_lazy('admin:products_lotestock_changelist'),
                        "permission": "core.permissions.ingreso_stock",
                    },
                    {
                        "title": _("Movimientos de Stock"),
                        "icon": "swap_horiz",
                        "link": reverse_lazy('admin:products_movimientostock_changelist'),
                        "permission": "core.permissions.ingreso_stock",
                    },
                    {
                        "title": _("Ajustes de Stock"),
                        "icon": "tune",
                        "link": reverse_lazy('admin:products_ajustestock_changelist'),
                        "permission": "core.permissions.ingreso_stock",
                        "badge": "dashboard.views.ajuste_stock",
                        "badge_variant": "danger",
                        "badge_style": "solid",
                    },
                ]
            },
            {
                "title": _("Configuración de productos"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Categorias"),
                        "icon": "settings",
                        "link": reverse_lazy('admin:products_categoria_changelist'),
                    },
                    {
                        "title": _("Sub Categorias"),
                        "icon": "settings",
                        "link": reverse_lazy('admin:products_subcategoria_changelist'),
                    },
                    {
                        "title": _("Marcas"),
                        "icon": "settings",
                        "link": reverse_lazy('admin:products_marca_changelist'),
                    },
                    {
                        "title": _("Etiquetas"),
                        "icon": "settings",
                        "link": reverse_lazy('admin:products_etiquetas_changelist'),
                    },
                    {
                        "title": _("Tokens para reseñas"),
                        "icon": "settings",
                        "link": reverse_lazy('admin:products_tokenreseña_changelist'),
                    }
                ]
            },
            {
                "title": _("Configuraciónes avanzadas"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Pagina de inicio"),
                        "icon": "home",
                        "link": reverse_lazy('admin:core_homesection_changelist'),
                    },
                    {
                        "title": _("Tus datos bancarios"),
                        "icon": "account_balance",
                        "link": reverse_lazy('admin:core_datosbancarios_change',args=[1]),
                    },
                    {
                        "title": _("Mercado Pago"),
                        "icon": "payment",
                        "link": reverse_lazy('admin:core_mercadopagoconfig_change',args=[1]),
                    },
                    {
                        "title": _("Configuración de envíos"),
                        "icon": "",
                        "link": reverse_lazy("admin:shipping_shippingconfig_changelist")
                    }
                ]
            },
            {
                "title": "Super admin",
                "items": [
                    {
                        "title": "Clientes",
                        "icon": "identity_platform",
                        "link": reverse_lazy("admin:customers_client_changelist"),
                        "permission": lambda request: request.user.is_superuser
                    },
                    {
                        "title": "Dominios",
                        "icon": "cloud",
                        "link": reverse_lazy("admin:customers_domain_changelist"),
                        "permission": lambda request: request.user.is_superuser
                    }
                ]
            },
        ],
    },
}