# Generated by Django 5.1.7 on 2025-03-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_perfilusuario_apellido_perfilusuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='preferencias_estado_pedido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='preferencias_promociones',
            field=models.BooleanField(default=False),
        ),
    ]
