# Generated by Django 5.1.7 on 2025-03-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_perfilusuario_preferencias_estado_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='calle_detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='provincia',
            field=models.CharField(blank=True, choices=[('A', 'Ciudad Autónoma de Buenos Aires'), ('B', 'Buenos Aires'), ('C', 'Catamarca'), ('D', 'Chaco'), ('E', 'Chubut'), ('F', 'Córdoba'), ('G', 'Corrientes'), ('H', 'Entre Ríos'), ('I', 'Formosa'), ('J', 'Jujuy'), ('K', 'La Pampa'), ('L', 'La Rioja'), ('M', 'Mendoza'), ('N', 'Misiones'), ('O', 'Neuquén'), ('P', 'Río Negro'), ('Q', 'Salta'), ('R', 'San Juan'), ('S', 'San Luis'), ('T', 'Santa Cruz'), ('U', 'Santa Fe'), ('V', 'Santiago del Estero'), ('W', 'Tierra del Fuego'), ('X', 'Tucumán')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
