# Generated by Django 5.1.7 on 2025-04-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_datosfacturacion_confirmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosfacturacion',
            name='confirmado',
        ),
    ]
