# Generated by Django 5.1.7 on 2025-04-01 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_datosfacturacion_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='token_verificacion',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
