# Generated by Django 5.1.7 on 2025-04-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_perfilusuario_token_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfacturacion',
            name='cuidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
