# Generated by Django 5.1.15 on 2026-01-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basico'), ('premium', 'Premium')], default='basic', max_length=7),
        ),
    ]
