# Generated by Django 5.1.15 on 2026-01-22 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0003_tipoatributo_remove_ajustestock_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='color',
        ),
        migrations.AddField(
            model_name='pedido',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variante'),
        ),
    ]
