# Generated by Django 5.1.8 on 2025-05-14 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_fecha_carrito_fecha_creacion_and_more'),
        ('products', '0045_categoria_updated_at_producto_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.colorproducto'),
        ),
    ]
