# Generated by Django 5.1.10 on 2025-10-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_checkoutdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdata',
            name='mixto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdata',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
