# Generated by Django 5.0.6 on 2024-09-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_atributos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
