# Generated by Django 5.1.7 on 2025-04-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_estimacionempaque_remove_producto_specs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_envio',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='EstimacionEmpaque',
        ),
    ]
