# Generated by Django 5.1.7 on 2025-04-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_producto_portada_producto_portada_100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='portada_100',
        ),
    ]
