# Generated by Django 5.1.7 on 2025-04-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_imagenproducto_imagen_alter_producto_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='imagen_100',
            field=models.ImageField(blank=True, null=True, upload_to='productos/imagenes/'),
        ),
    ]
