# Generated by Django 5.1.7 on 2025-04-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_imagenproducto_imagen_100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificaciontecnica',
            name='datos',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
