# Generated by Django 5.1.7 on 2025-04-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_especificaciontecnica_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
