# Generated by Django 5.1.7 on 2025-04-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_producto_precio_anterior_alter_producto_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_anterior',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
