# Generated by Django 5.1.8 on 2025-04-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_categoria_descripcion_seo_producto_descripcion_seo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
