# Generated by Django 5.1.8 on 2025-04-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_subcategoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
