# Generated by Django 5.1.8 on 2025-04-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='inhabilitar',
            field=models.BooleanField(default=False),
        ),
    ]
