# Generated by Django 5.1.8 on 2025-04-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_producto_inhabilitar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sub_categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='sub_categorias',
            field=models.ManyToManyField(related_name='productos', to='products.subcategoria'),
        ),
    ]
