# Generated by Django 5.0.6 on 2025-03-07 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_fecha_carrito_fecha_creacion_and_more'),
        ('payment', '0002_alter_payments_options_remove_payments_date_created_and_more'),
        ('users', '0003_remove_perfilusuario_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='payment.payments')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='users.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.pedido')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='payment.historialcompras')),
            ],
        ),
    ]
