# Generated by Django 5.1.15 on 2026-01-27 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_homeproductgrid_criterio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('zipnova', 'Zipnova (Argentina)')], default='zipnova', max_length=50)),
                ('auth_type', models.CharField(choices=[('basic', 'Basic Auth (Legacy/Manual)'), ('oauth', 'OAuth 2.0')], default='basic', max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('defaults', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_config', to='core.tienda')),
            ],
        ),
    ]
