# Generated by Django 5.1.15 on 2026-01-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingconfig',
            name='shop',
        ),
    ]
