# Generated by Django 5.0.6 on 2025-03-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={},
        ),
        migrations.RemoveField(
            model_name='payments',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='date_of_expiration',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='idetification_number',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='idetification_type',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
