# Generated by Django 5.1.7 on 2025-03-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_historialcompras_forma_de_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompras',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='historialcompras',
            name='pagos',
            field=models.ManyToManyField(blank=True, to='payment.pagorecibidomp'),
        ),
    ]
