# Generated by Django 5.1.7 on 2025-03-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_comprobantetransferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantetransferencia',
            name='imagen',
            field=models.FileField(upload_to='comprobantes/'),
        ),
    ]
