# Generated by Django 5.1.7 on 2025-04-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_rename_imagen_comprobantetransferencia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompras',
            name='recibir_mail',
            field=models.BooleanField(default=False),
        ),
    ]
