# Generated by Django 5.1.7 on 2025-04-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_remove_historialcompras_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
