# Generated by Django 5.1.8 on 2025-04-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_alter_historialcompras_merchant_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompras',
            name='fecha_finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialcompras',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('preparando pedido', 'Preparando pedido'), ('enviado', 'Enviado'), ('finalizado', 'Finalizado'), ('arrepentido', 'Arrepentido')], default='pendiente', max_length=20),
        ),
    ]
