# Generated by Django 5.1.8 on 2025-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_historialcompras_fecha_finalizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente🟡'), ('confirmado', 'Confirmado🟢'), ('rechazado', 'Rechazado🔴'), ('preparando pedido', 'Preparando pedido🔵'), ('enviado', 'Enviado🟣'), ('finalizado', 'Finalizado⚪'), ('arrepentido', 'Arrepentido⭕')], default='pendiente', max_length=20),
        ),
    ]
