# Generated by Django 5.1.8 on 2025-04-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_remove_historialcompras_verificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='estado_staff',
            field=models.CharField(choices=[('no verificado', 'No verificado'), ('revision en curso', 'Revisión en curso'), ('esperando respuesta', 'Esperando respuesta del cliente'), ('pedido realizado', 'Pedido realizado al proveedor'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('transferencia recibida', 'Transferencia recibida')], default='no verificado', max_length=50),
        ),
    ]
