# Generated by Django 5.1.15 on 2026-04-20 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0005_remove_datosfacturacion_email'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado'), ('arrepentido', 'Arrepentido'), ('listo para retirar', 'Listo para retirar'), ('enviado', 'Enviado')], default='pendiente', max_length=20)),
                ('forma_de_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('requiere_revision', models.BooleanField(default=True)),
                ('pagos', models.ManyToManyField(blank=True, editable=False, to='payment.pagorecibidomp')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='orders.venta')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='DatosFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('razon_social', models.CharField(blank=True, max_length=255)),
                ('dni_cuit', models.CharField(max_length=20)),
                ('condicion_iva', models.CharField(choices=[('A', 'Responsable Inscripto'), ('B', 'Consumidor Final'), ('C', 'Monotributo'), ('E', 'Exento'), ('N', 'No Responsable')], max_length=1)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('provincia', models.CharField(choices=[('A', 'Ciudad Autónoma de Buenos Aires'), ('B', 'Buenos Aires'), ('C', 'Catamarca'), ('H', 'Chaco'), ('U', 'Chubut'), ('X', 'Córdoba'), ('W', 'Corrientes'), ('E', 'Entre Ríos'), ('P', 'Formosa'), ('Y', 'Jujuy'), ('L', 'La Pampa'), ('F', 'La Rioja'), ('M', 'Mendoza'), ('N', 'Misiones'), ('Q', 'Neuquén'), ('R', 'Río Negro'), ('I', 'Salta'), ('J', 'San Juan'), ('D', 'San Luis'), ('Z', 'Santa Cruz'), ('S', 'Santa Fe'), ('G', 'Santiago del Estero'), ('V', 'Tierra del Fuego'), ('T', 'Tucumán')], max_length=1)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facturacion', to='orders.venta')),
            ],
            options={
                'verbose_name': 'Facturación',
                'verbose_name_plural': 'Datos de Facturación',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.variante')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='orders.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
    ]
