# Generated by Django 5.1.15 on 2026-04-16 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('payment', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresostock',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotestock',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='products.ingresostock'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.lotestock'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='atributos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='products.atributo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='productos', to='products.etiquetas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventospromociones'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.marca'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producto'),
        ),
        migrations.AddField(
            model_name='ingresostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_stock', to='products.producto'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_producto', to='products.producto'),
        ),
        migrations.AddField(
            model_name='especificaciontecnica',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='products.producto'),
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.producto'),
        ),
        migrations.AddField(
            model_name='ingresostock',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.proveedor'),
        ),
        migrations.AddField(
            model_name='reseñaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='products.producto'),
        ),
        migrations.AddField(
            model_name='reseñaproducto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='products.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sub_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='products.subcategoria'),
        ),
        migrations.AddField(
            model_name='tokenreseña',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto'),
        ),
        migrations.AddField(
            model_name='tokenreseña',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valoratributo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='products.tipoatributo'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='variante',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío si la imagen es general. Seleccionar un valor (ej: Rojo) si la imagen es específica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_asociadas', to='products.valoratributo'),
        ),
        migrations.AddField(
            model_name='variante',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='products.producto'),
        ),
        migrations.AddField(
            model_name='variante',
            name='valores',
            field=models.ManyToManyField(to='products.valoratributo'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variante'),
        ),
        migrations.AddField(
            model_name='ingresostock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_stock', to='products.variante'),
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variante'),
        ),
    ]
