# Generated by Django 5.0.6 on 2024-06-24 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='products.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(),
        ),
    ]
