# Generated by Django 5.1.14 on 2025-11-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_dolar',
            new_name='precio_divisa',
        ),
    ]
