# Generated by Django 5.1.15 on 2026-01-22 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ajustestock',
            name='color',
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ingresostock',
            name='producto_color',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='producto_color',
        ),
        migrations.AlterField(
            model_name='tokenreseña',
            name='token',
            field=models.UUIDField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='products.tipoatributo')),
            ],
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='filtro_valor',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío si la imagen es general. Seleccionar un valor (ej: Rojo) si la imagen es específica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_asociadas', to='products.valoratributo'),
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='products.producto')),
                ('valores', models.ManyToManyField(to='products.valoratributo')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
            },
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variante'),
        ),
        migrations.AddField(
            model_name='ingresostock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variante'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variante'),
        ),
    ]
