# Generated by Django 5.1.15 on 2026-04-20 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustestock',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_stock', to='orders.venta'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.venta'),
        ),
    ]
