# Generated by Django 5.1.14 on 2025-11-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_precio_dolar_producto_precio_divisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_evento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
