# Generated by Django 5.1.15 on 2026-01-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_pedido_color_pedido_variante'),
        ('payment', '0003_remove_ventadetalle_color_ventadetalle_variante'),
        ('products', '0003_tipoatributo_remove_ajustestock_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoratributo',
            name='metadatos',
            field=models.JSONField(blank=True, help_text='Ej: #ffffff (Para utilizar el color blanco)', null=True),
        ),
        migrations.AlterField(
            model_name='tipoatributo',
            name='nombre',
            field=models.CharField(help_text='Ej: Color, Talle, Material, Voltaje', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoatributo',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='valoratributo',
            name='valor',
            field=models.CharField(help_text='Ej: Blanco, XL, Plastico, 220v', max_length=50),
        ),
        migrations.AlterField(
            model_name='variante',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='ColorProducto',
        ),
    ]
