# Generated by Django 5.1.14 on 2025-11-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_imagen_banner_eventospromociones_logo'),
        ('products', '0003_producto_precio_base_producto_precio_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventospromociones'),
        ),
    ]
