# Generated by Django 5.1.15 on 2026-01-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_valoratributo_metadatos_alter_tipoatributo_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributo',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='atributos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='products.atributo'),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='valor',
            field=models.CharField(max_length=50),
        ),
    ]
