# Generated by Django 5.0.6 on 2024-06-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_marca_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(default='marcas/default.jpg', upload_to='marcas/'),
        ),
    ]
