# Generated by Django 5.1.15 on 2026-01-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_atributo_producto_producto_atributos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributo',
            name='nombre',
            field=models.CharField(help_text='Ej: Almacemaniento, Consumo electrico', max_length=50),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='valor',
            field=models.CharField(help_text='Ej: 256 GB, 200W', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='atributo',
            unique_together={('nombre', 'valor')},
        ),
    ]
