# Generated by Django 5.1.14 on 2025-11-28 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_venta_productos_ventadetalle'),
        ('products', '0006_movimientostock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientostock',
            name='referencia',
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.venta'),
        ),
    ]
