# Generated by Django 5.1.15 on 2026-01-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_atributo_nombre_alter_atributo_valor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributo',
            options={'ordering': ['nombre', 'valor']},
        ),
        migrations.AlterField(
            model_name='valoratributo',
            name='metadatos',
            field=models.CharField(blank=True, help_text='Ej: #ffffff (Para utilizar el color blanco)', max_length=50, null=True),
        ),
    ]
