# Generated by Django 5.1.14 on 2025-11-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_movimientostock_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorproducto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
