# Generated by Django 5.1.15 on 2026-01-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_atributo_options_alter_valoratributo_metadatos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenproducto',
            old_name='filtro_valor',
            new_name='variante',
        ),
    ]
