# Generated by Django 5.0.6 on 2024-08-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_atributos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atributos',
        ),
    ]
