# Generated by Django 5.1.15 on 2026-01-27 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_filtro_valor_imagenproducto_variante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresostock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_stock', to='products.variante'),
        ),
    ]
