# Generated by Django 5.1.14 on 2025-11-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_ajustestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresostock',
            name='margen_porcentaje',
        ),
        migrations.RemoveField(
            model_name='ingresostock',
            name='margen_valor',
        ),
    ]
