# Generated by Django 5.1.15 on 2026-01-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_ingresostock_margen_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorproducto',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterModelOptions(
            name='especificaciontecnica',
            options={'ordering': ['clave'], 'verbose_name': 'Especificacion Técnica', 'verbose_name_plural': 'Especificaciones Técnicas'},
        ),
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='ingresostock',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Ingreso de Stock', 'verbose_name_plural': 'Ingresos de Stock'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='reseñaproducto',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
    ]
