# Generated by Django 5.1.7 on 2025-03-28 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_atributo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='products.producto')),
            ],
        ),
    ]
