# Generated by Django 5.1.7 on 2025-03-28 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_especificaciontecnica'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEspecificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='especificaciontecnica',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categoriaespecificacion'),
        ),
    ]
