# Generated by Django 5.1.7 on 2025-03-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_categoriaespecificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificaciontecnica',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='especificaciontecnica',
            name='valor',
        ),
        migrations.AddField(
            model_name='especificaciontecnica',
            name='datos',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
