# Generated by Django 5.1.7 on 2025-03-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_especificaciontecnica_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificaciontecnica',
            name='datos',
            field=models.JSONField(default=dict),
        ),
    ]
