# Generated by Django 5.1.7 on 2025-03-29 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_especificaciontecnica_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimacionEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, unique=True)),
                ('largo_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ancho_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alto_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='specs',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.estimacionempaque'),
        ),
    ]
