# Generated by Django 5.1.7 on 2025-04-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_producto_categoria_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
