# Generated by Django 5.1.7 on 2025-04-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_producto_portada_100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(upload_to='productos/imagenes/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='productos/portadas/'),
        ),
    ]
