# Generated by Django 5.1.7 on 2025-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_imagenproducto_imagen_100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen_100',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='productos/imagenes/'),
        ),
    ]
