# Generated by Django 5.1.8 on 2025-04-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_producto_precio_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion_seo',
            field=models.CharField(blank=True, help_text='Descripción corta para SEO (aparece en Google). Máximo 160 caracteres.', max_length=160),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_seo',
            field=models.CharField(blank=True, help_text='Descripción corta para SEO (aparece en Google). Máximo 160 caracteres.', max_length=160),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='descripcion_seo',
            field=models.CharField(blank=True, help_text='Descripción corta para SEO (aparece en Google). Máximo 160 caracteres.', max_length=160),
        ),
    ]
