# Generated by Django 5.1.8 on 2025-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
