# Generated by Django 5.1.8 on 2025-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='seccion_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
