# Generated by Django 5.1.8 on 2025-04-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_categoria_seccion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en el menú'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='seccion_id',
            field=models.CharField(blank=True, choices=[('prod_item-componentes', 'Componentes'), ('prod_item-computos', 'PC y Notebooks'), ('prod_item-accesorios', 'Periféricos'), ('prod_item-celulares', 'Celulares'), ('prod_item-impresion', 'Impresión'), ('prod_item-gaming', 'Gaming'), ('prod_item-marcas', 'Marcas')], max_length=50, null=True),
        ),
    ]
