# Generated by Django 5.1.8 on 2025-05-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_categoria_seccion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('hex', models.CharField(default='#ffffff', help_text='Color en HEXADECIMAL (#ffffff)', max_length=7)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='products.producto')),
            ],
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='products.colorproducto'),
        ),
    ]
