# Generated by Django 5.1.8 on 2025-05-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_colorproducto_imagenproducto_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
