# Generated by Django 5.1.8 on 2025-05-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_categoria_updated_at_producto_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='seccion_id',
            field=models.CharField(blank=True, choices=[('componentes', 'Componentes'), ('computos', 'PC y Notebooks'), ('accesorios', 'Accesorios'), ('móviles', 'Móviles'), ('impresion', 'Impresión')], max_length=50, null=True),
        ),
    ]
