# Generated by Django 5.1.8 on 2025-05-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_categoria_seccion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='seccion_id',
            field=models.CharField(blank=True, choices=[('componentes', 'Componentes'), ('computos', 'PC y Notebooks'), ('accesorios', 'Accesorios'), ('dispositivos', 'Dispositivos'), ('impresion', 'Impresión')], max_length=50, null=True),
        ),
    ]
