# Generated by Django 5.1.10 on 2025-10-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_categoria_seccion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='seccion_id',
        ),
    ]
