# Generated by Django 5.1.10 on 2025-10-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_remove_categoria_orden_remove_categoria_seccion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificaciontecnica',
            name='categoria',
        ),
        migrations.AlterModelOptions(
            name='especificaciontecnica',
            options={'ordering': ['clave']},
        ),
        migrations.RemoveField(
            model_name='especificaciontecnica',
            name='datos',
        ),
        migrations.AddField(
            model_name='especificaciontecnica',
            name='clave',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='especificaciontecnica',
            name='valor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='CategoriaEspecificacion',
        ),
    ]
