# Generated by Django 5.1.10 on 2025-10-14 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_reseñaproducto'),
        ('users', '0023_alter_datosfacturacion_condicion_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñaproducto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.perfilusuario'),
        ),
    ]
