# Generated by Django 5.1.10 on 2025-10-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_alter_reseñaproducto_usuario'),
        ('users', '0025_rename_calle_perfilusuario_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñaproducto',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario'),
            preserve_default=False,
        ),
    ]
