# Generated by Django 5.1.10 on 2025-10-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_alter_reseñaproducto_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenproducto',
            old_name='imagen_100',
            new_name='imagen_150',
        ),
    ]
