# Generated by Django 5.1.10 on 2025-10-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_rename_imagen_100_imagenproducto_imagen_150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenproducto',
            old_name='imagen_150',
            new_name='imagen_200',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='portada',
        ),
    ]
