# Generated by Django 5.1.10 on 2025-10-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_rename_imagen_150_imagenproducto_imagen_200_and_more'),
        ('users', '0028_remove_perfilusuario_preferencias_promociones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='imagen',
        ),
        migrations.AddField(
            model_name='marca',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_color', to='products.colorproducto'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_producto', to='products.producto'),
        ),
        migrations.AlterField(
            model_name='reseñaproducto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario'),
        ),
    ]
