# Generated by Django 5.1.10 on 2025-10-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_remove_marca_imagen_marca_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
