# Generated by Django 5.1.10 on 2025-11-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_alter_marca_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquetas',
            name='producto',
        ),
        migrations.AddField(
            model_name='etiquetas',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='productos', to='products.etiquetas'),
        ),
        migrations.AlterField(
            model_name='etiquetas',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
