# Generated by Django 5.1.10 on 2025-11-02 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_remove_etiquetas_producto_etiquetas_slug_and_more'),
        ('users', '0028_remove_perfilusuario_preferencias_promociones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñaproducto',
            name='comentario',
            field=models.TextField(max_length=250),
        ),
        migrations.CreateModel(
            name='TokenReseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario')),
            ],
        ),
    ]
