# Generated by Django 5.1.10 on 2025-11-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_alter_reseñaproducto_comentario_tokenreseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenreseña',
            name='token',
            field=models.UUIDField(blank=True, editable=False, unique=True),
        ),
    ]
