# Generated by Django 5.1.10 on 2025-11-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_alter_tokenreseña_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproducto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
